apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: LWIgVGVzdEAxMjMK
  MYSQL_DATABASE: YmFua2FwcGRi



---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "bankappdb"


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-pd-balanced-rwo-sc
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain 
parameters:
  type: pd-balanced 


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: gke-pd-balanced-rwo-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql 
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-images
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:  
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1 
kind: Service 
metadata:
  name: mysel-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  
---

apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp 
  template:
    metadata:
      name: bankapp-pod 
      labels:
        app: bankapp
    spec:
     containers:
      - name: bankapp
        image: adijaiswal/bankapp:latest
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysel-svc:3306/bankappdb?useSSL=false&serverTimezone=UTC
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---


kind: Service
apiVersion: v1
metadata:
  name:  bankapp-svc
spec:
  selector:
    app:  bankapp
  type:  LoadBalancer 
  ports:
  - name: bankapp-port
    port:  80
    targetPort:  8080