apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: web
  type: {{ .Values.service.type }}
  ports:
    - name: bankapp-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
