apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data: 
  db-password: QWRtaW40dTEyMyFAIw==

# Base64 of KalyanReddy13
# https://www.base64encode.org/
# Base64 of Admin4u123!@# is QWRtaW40dTEyMyFAIw==