apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-pd-balanced-rwo-sc
  namespace: webapps
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain 
parameters:
  type: pd-balanced 

---

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mysql-pv-claim 
  namespace: webapps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-pd-balanced-rwo-sc
  resources:
    requests:
      storage: 8Gi
  
