apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: jenkins-role
  namespace: webapps
rules:
   # Permissions for core API resources
  - apiGroups: [""]
    resources:
      - secrets 
      - configmaps 
      - persistentvolumeclaims 
      - service 
      - pod 
    verbs: ["get", "list", "watch", "create", "update","delete", "patch"]
  
  # Permissions for apps API group
  - apiGroups: ["apps"]
    resources:
      - deployment 
      - replicasets 
      - statefulsets 
    verbs: ["list","get","watch","create","update","delete","patch"]

  # Permissions for networking API group 
  - apiGroups: ["networking.k8s.io"]
    resources:
     - ingresses 
    verbs : ["list","watch","get","create","update","delete","patch"]
  
  # permission for autoscaling API group
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "delete","patch"]